---
kind: golang.Build
spec:
  outputs:
    capi-linux-amd64:
      GOOS: linux
      GOARCH: amd64
    capi-linux-arm64:
      GOOS: linux
      GOARCH: arm64
    capi-linux-armv7:
      GOOS: linux
      GOARCH: arm
      GOARM: 7
    capi-darwin-amd64:
      GOOS: darwin
      GOARCH: amd64
    capi-darwin-arm64:
      GOOS: darwin
      GOARCH: arm64
    capi-windows-amd64.exe:
      GOOS: windows
      GOARCH: amd64